In [1]:
import numpy as np

In [2]:
ar=np.random.randn(4)
ar

array([-0.39148907, -1.1367594 ,  0.76555357, -1.48508081])

In [3]:
ar=np.random.randn(4,3)
ar

array([[ 0.8849825 ,  0.4686906 , -1.25951107],
       [ 0.48576868,  1.1072474 , -0.7123329 ],
       [ 0.24586611,  0.1891131 ,  0.09013126],
       [ 0.62463909, -0.05476707, -0.53294989]])

In [4]:
ar=np.random.randn(4,4,2)
ar

array([[[-0.10823572, -0.26000638],
        [ 0.5444359 ,  1.45609579],
        [-0.3710491 , -0.89290446],
        [ 0.36292997, -1.16636918]],

       [[ 2.27982296,  0.08742318],
        [ 0.14284834,  0.65204301],
        [-0.95630864,  1.60637915],
        [-0.62640258,  0.45495904]],

       [[ 0.29603805, -2.17884263],
        [ 1.38484792,  0.3020009 ],
        [-0.84464352,  0.4755387 ],
        [-1.94331238, -0.67287305]],

       [[ 0.38488037, -0.81245468],
        [ 1.52605246, -0.05627536],
        [-0.06671464, -0.93310016],
        [-0.38706435, -1.86895333]]])

In [5]:
ar1=np.random.ranf(4)
ar1

array([0.72460895, 0.01070447, 0.0783956 , 0.69438131])

In [6]:
ar11=np.random.random_sample((2,3))
ar11

array([[0.10191617, 0.56307708, 0.71665788],
       [0.74845898, 0.92861288, 0.04159288]])

In [7]:
ar21=np.random.ranf(2)
ar21

array([0.34267796, 0.28979881])

In [8]:
ar31=np.random.random_sample((3,4))
ar31

array([[0.47642682, 0.55333327, 0.88489965, 0.74720912],
       [0.2574518 , 0.95613957, 0.43604031, 0.71539561],
       [0.36367171, 0.76796734, 0.04443247, 0.85993795]])

In [9]:
ar221=np.random.ranf((3,2))
ar221

array([[0.08387581, 0.80223234],
       [0.35837424, 0.14232973],
       [0.01114478, 0.93524527]])

In [10]:
ar24=np.random.ranf((3,2,2))
ar24

array([[[0.35232316, 0.17880226],
        [0.00948175, 0.74585105]],

       [[0.30303482, 0.61574941],
        [0.02127698, 0.15347062]],

       [[0.00667456, 0.35005661],
        [0.98198793, 0.60784437]]])

In [11]:
ar3=np.random.random_sample((2,3,4))
ar3


array([[[0.04316517, 0.38208155, 0.95401925, 0.82254621],
        [0.29792829, 0.60772634, 0.77445162, 0.80668594],
        [0.2400727 , 0.43606605, 0.82797402, 0.64018948]],

       [[0.71784054, 0.54635162, 0.72554655, 0.58897799],
        [0.32078257, 0.11386574, 0.71273924, 0.6467239 ],
        [0.59620643, 0.54231905, 0.98730765, 0.22976144]]])

In [12]:
np.sort(ar3)


array([[[0.04316517, 0.38208155, 0.82254621, 0.95401925],
        [0.29792829, 0.60772634, 0.77445162, 0.80668594],
        [0.2400727 , 0.43606605, 0.64018948, 0.82797402]],

       [[0.54635162, 0.58897799, 0.71784054, 0.72554655],
        [0.11386574, 0.32078257, 0.6467239 , 0.71273924],
        [0.22976144, 0.54231905, 0.59620643, 0.98730765]]])

In [13]:
arr1=np.random.randint(1,50, size=(2,2))
arr1

array([[29, 18],
       [ 7, 18]])

In [14]:
np.sort(arr1)

array([[18, 29],
       [ 7, 18]])

In [15]:
np.sort(arr1,axis=0)

array([[ 7, 18],
       [29, 18]])

In [16]:
np.sort(arr1,axis=1)

array([[18, 29],
       [ 7, 18]])

In [17]:
arr=np.random.randint(1,20,size=(3,2))
arr

array([[13,  1],
       [12,  6],
       [14, 18]])

In [36]:
np.sort(arr,axis=0)      # smallest value of column

array([[12,  1],
       [13,  6],
       [14, 18]])

In [38]:
np.sort(arr,axis=1)    # inceasing oderdr by row

array([[ 1, 13],
       [ 6, 12],
       [14, 18]])

# Stastical Variables

In [41]:
np.mean(arr)

10.666666666666666

In [45]:
np.median(arr)

12.5

In [49]:
np.std(arr)

5.587684871413403

In [51]:
np.var(arr)

31.222222222222218

In [55]:
np.nan       # it denotes the null values  or empty values.


nan

In [58]:
from scipy import stats

In [82]:
# to finding the mode.
arr1=np.array([2,3,4,6,7,8,9,4,3,3,2,4,6,7,4,2])
mode=stats.mode(arr1,keepdims=False)
mode[0]

4

In [74]:
# to finding the unique value 
arr1=np.array([2,3,4,6,7,8,9,4,3,3,2,4,6,7,4,2])
np.unique(arr1)

array([2, 3, 4, 6, 7, 8, 9])

# Logarithmic Function

In [85]:
 np.log(10)

2.302585092994046

In [87]:
np.log(2)

0.6931471805599453

In [91]:
np.pi

3.141592653589793

# Trignometry

In [94]:
# Degree to radian
np.pi/6

0.5235987755982988

In [96]:
degree_30= np.pi/6
degree_30

0.5235987755982988

In [100]:
degree_45= np.pi/4
degree_45

0.7853981633974483

In [102]:
degree_60= np.pi/3
degree_60

1.0471975511965976

In [104]:
degree_90= np.pi/2
degree_90

1.5707963267948966

In [106]:
degree_180= np.pi
degree_180

3.141592653589793

In [110]:
np.sin(np.pi/6)

0.49999999999999994

In [112]:
np.sin(np.pi/4)

0.7071067811865476

In [114]:
np.sin(np.pi/3)

0.8660254037844386

In [116]:
np.sin(np.pi/2)

1.0

In [118]:
np.sin(np.pi)

1.2246467991473532e-16

In [120]:
np.cos(np.pi/6)

0.8660254037844387

In [122]:
np.cos(np.pi/4)

0.7071067811865476

In [124]:
np.cos(np.pi/3)

0.5000000000000001

In [126]:
np.cos(np.pi/2)

6.123233995736766e-17

In [128]:
np.cos(np.pi)

-1.0

In [130]:
np.tan(np.pi/6)

0.5773502691896257

In [132]:
np.tan(np.pi/4)

0.9999999999999999

In [134]:
np.tan(np.pi/3)

1.7320508075688767

In [136]:
np.tan(np.pi/2)

1.633123935319537e+16

In [138]:
# degree to radiant convert.
arr=np.array([0,30,45,60,90])
rad=np.deg2rad(arr)
rad

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [148]:
#  radiant to degree convert.
arr=np.array([0,30,45,60,90])
rad=np.rad2deg(arr)
rad

array([   0.        , 1718.87338539, 2578.31007809, 3437.74677078,
       5156.62015618])

# Linear Algebra

In [144]:
A=np.array([[3,4],[5,6]])
B=np.array([15,20])
np.linalg.solve(A,B)

array([-5. ,  7.5])

# Inverse

In [153]:
A=np.array([[2,3,5],[3,-5,7],[4,2,10]])
A

array([[ 2,  3,  5],
       [ 3, -5,  7],
       [ 4,  2, 10]])

In [157]:
np.linalg.inv(A)

array([[ 16.  ,   5.  , -11.5 ],
       [  0.5 ,  -0.  ,  -0.25],
       [ -6.5 ,  -2.  ,   4.75]])

# Append

In [160]:
import numpy as np

In [162]:
arr=np.random.randint(1,50,size=(3,3))

In [164]:
arr1=np.random.randint(1,50,size=(3,3))

In [166]:
arr

array([[38, 24, 39],
       [23, 25,  1],
       [34, 17, 36]])

In [168]:
arr1

array([[26, 42, 41],
       [42, 43, 49],
       [15, 49, 45]])

In [170]:
np.append(arr,arr1)

array([38, 24, 39, 23, 25,  1, 34, 17, 36, 26, 42, 41, 42, 43, 49, 15, 49,
       45])

In [172]:
np.add(arr,arr1)

array([[64, 66, 80],
       [65, 68, 50],
       [49, 66, 81]])

In [174]:
np.append(arr,arr1,axis=0)      

array([[38, 24, 39],
       [23, 25,  1],
       [34, 17, 36],
       [26, 42, 41],
       [42, 43, 49],
       [15, 49, 45]])

In [176]:
np.append(arr,arr1,axis=1)

array([[38, 24, 39, 26, 42, 41],
       [23, 25,  1, 42, 43, 49],
       [34, 17, 36, 15, 49, 45]])

# Concatenate

In [179]:
a11=np.append(arr,arr1,axis=0)  
a12=np.append(arr,arr1,axis=1)

In [191]:
array1=np.array([2,3,4,5,6])
array2=np.array([10,20,30,40,50])

In [193]:
np.concatenate([array1,array2],axis=0)

array([ 2,  3,  4,  5,  6, 10, 20, 30, 40, 50])

# Iter

In [197]:
for i in array1:
    print(i)

2
3
4
5
6


In [199]:
for i in array2:
    print(i)

10
20
30
40
50


# ndenumerate

In [209]:
for i,j in np. ndenumerate (array1):
    print(i,j)

(0,) 2
(1,) 3
(2,) 4
(3,) 5
(4,) 6


In [212]:
np.ndenumerate(array1)

In [224]:
array1=np.random.randint(0,1, size=[3,3])
array1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [240]:
# Where
array=np.array([[2,3],[4,5],[6,7],[4,5],[6,4],[7,8]])
a=np.where(array==4)
a

(array([1, 3, 4], dtype=int64), array([0, 0, 1], dtype=int64))

In [242]:
array[1][0]

4

In [246]:
array[3][0]

4

In [248]:
array[4][0]

6

In [251]:
q=np.array([1,2,3,66,45,33,])
np.max(q)

66

In [253]:
q=np.array([[1,2,3,66,45,33,]])
np.max(q)

66

In [255]:
q=np.array([[1,2,3],[66,45,33]])
np.max(q)

66

In [257]:
np.min(q)

1

In [259]:
np.max(q)

66

In [261]:
np.full([3,3],0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [265]:
s=np.full([2,2],30)
s

array([[30, 30],
       [30, 30]])

In [273]:
s1=s*2
s1

array([[60, 60],
       [60, 60]])

In [275]:
s+s1

array([[90, 90],
       [90, 90]])

In [277]:
np.append(s,s1,axis=1)

array([[30, 30, 60, 60],
       [30, 30, 60, 60]])

In [279]:
np.append(s,s1,axis=0)

array([[30, 30],
       [30, 30],
       [60, 60],
       [60, 60]])