In [3]:
import numpy as np

In [10]:
l1=[1,2,3,4,5,6]   # List
a=np.array(l1)
a

array([1, 2, 3, 4, 5, 6])

In [12]:
t1=(1,2,3,4,5,6)     # Tuple
a=np.array(t1)
a

array([1, 2, 3, 4, 5, 6])

In [14]:
s=" s h r e y a"   # string
a=np.array(s)
a

array(' s h r e y a', dtype='<U12')

In [16]:
c= 4+8j            # complex
a=np.array(c)
a

array(4.+8.j)

In [18]:
# conveted into data types

arr1=np.array([1,2,3,4,56,6],dtype="float")
arr1

array([ 1.,  2.,  3.,  4., 56.,  6.])

In [22]:
a=np.array([ 1.,  2.,  3.,  4., 56.,  6.],dtype="int")
a

array([ 1,  2,  3,  4, 56,  6])

In [26]:
l2=[33,21,44,67,88,987,66]
z=np.array(l2,dtype="float")
z

array([ 33.,  21.,  44.,  67.,  88., 987.,  66.])

In [34]:
# to check the dimension indicate the square brackets[[[
z.ndim

1

In [40]:
q1=np.array([[2,3],[1,3],[4,3],[8,9]])
q1

array([[2, 3],
       [1, 3],
       [4, 3],
       [8, 9]])

In [42]:
q1.ndim

2

In [44]:
q1.shape

(4, 2)

In [46]:
q1=np.array([[[2,3],[1,3],[4,3],[8,9]]])
q1

array([[[2, 3],
        [1, 3],
        [4, 3],
        [8, 9]]])

In [48]:
print(q1.ndim)  
print(q1.shape)

3
(1, 4, 2)


In [52]:
q1

array([[[2, 3],
        [1, 3],
        [4, 3],
        [8, 9]]])

In [74]:
q1[0][3]

array([8, 9])

In [78]:
q1[0][1]

array([1, 3])

In [68]:
q1

array([[[2, 3],
        [1, 3],
        [4, 3],
        [8, 9]]])

In [97]:
q1[0][3][0]

8

In [105]:
q1[0][2][1]

3

In [115]:
a=np.array([[[2,4, 3],
        [1,2, 3],
        [4,5, 3],
        [8,4, 9]]])

In [117]:
a[0]

array([[2, 4, 3],
       [1, 2, 3],
       [4, 5, 3],
       [8, 4, 9]])

In [129]:
a[0][2][1]

2

In [135]:
a[0][3][1]

4

In [139]:
a[0][1][2]

3

In [141]:
a[0][3][1]

4

In [147]:
a[0][3][1]

4

In [149]:
a[0][0][2]

3

In [151]:
a[0][1][2]

3

In [153]:
a[0][1]

array([1, 2, 3])

In [157]:
a[0][2]

array([4, 5, 3])

In [159]:
a[0][3]

array([8, 4, 9])

In [163]:
a[0][0]

array([2, 4, 3])

In [165]:
a[0][0][1]

4

In [167]:
a

array([[[2, 4, 3],
        [1, 2, 3],
        [4, 5, 3],
        [8, 4, 9]]])

In [175]:
a[0][1][0]

1

In [177]:
b=np.array([[1,2],[2,3],[4,5]])
b

array([[1, 2],
       [2, 3],
       [4, 5]])

In [181]:
b[0]

array([1, 2])

In [183]:
b[1]

array([2, 3])

In [185]:
b[2]

array([4, 5])

In [187]:
b[2][0]

4

In [189]:
b[1][1]

3