In [1]:
import numpy as np

# Shape

In [3]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)
print("shape of array",a.shape)
print("Dimensions of array is:",a.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
shape of array (12,)
Dimensions of array is: 1


In [4]:
1*12
12*1
3*4
4*3
6*2
2*6

12

In [5]:
ar12 = a.reshape(3,4)
print(ar12)
print("shape of array",ar12.shape)
print("Dimensions of array is:",ar12.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
shape of array (3, 4)
Dimensions of array is: 2


In [6]:
ar12 = a.reshape(4,3)
print(ar12)
print("shape of array",ar12.shape)
print("Dimensions of array is:",ar12.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
shape of array (4, 3)
Dimensions of array is: 2


In [7]:
ar12 = a.reshape(2,6)
print(ar12)
print("shape of array",ar12.shape)
print("Dimensions of array is:",ar12.ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
shape of array (2, 6)
Dimensions of array is: 2


# possibilities to convert  1D to 3D (Using reshape)

In [9]:
ar = a.reshape(1,2,6)
print(ar)
print("shape of array",ar.shape)
print("Dimensions of array is:",ar.ndim)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]]
shape of array (1, 2, 6)
Dimensions of array is: 3


In [10]:
ar = a.reshape(1,3,4)
print(ar)
print("shape of array",ar.shape)
print("Dimensions of array is:",ar.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
shape of array (1, 3, 4)
Dimensions of array is: 3


In [11]:
ar = a.reshape(1,4,3)
print(ar)
print("shape of array",ar.shape)
print("Dimensions of array is:",ar.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
shape of array (1, 4, 3)
Dimensions of array is: 3


In [12]:
# converted into array into a list (flatten list)


a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=a.reshape(9,)
list(b)

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
l1=a.tolist()      # another way to converting array into list.
l1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])       # another way to converting array into list.
b=a.reshape(-1)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# take a list by even no
list=[1, 2, 3, 4, 5, 6, 7, 8, 9]
l2=[]
for i in list:
    if i %2==0:
        l2.append(i)
ar1=np.array(l2)

In [16]:
ar1

array([2, 4, 6, 8])

In [17]:
list=[1, 2, 3, 4, 5, 6, 7, 8, 9]                    # another way.
al=np.array([i for i in list if i %2==0])
al

array([2, 4, 6, 8])

In [18]:
a1=np.array([1,2,3,4,5])     # no of elemenet are should be same in both array.
a2=np.array([6,7,8,9,1])
a1+a2

array([ 7,  9, 11, 13,  6])

In [19]:
a1=np.array([8,2,3,4,5])     # no of elemenet are should be same in both array.
a2=np.array([6,7,8,9,7])
a1*a2

array([48, 14, 24, 36, 35])

In [20]:
a1=np.array([8,2,3,4,5])     # no of elemenet are should be same in both array.
a2=np.array([6,7,8,9,7])
np.multiply(a1,a2)

array([48, 14, 24, 36, 35])

In [21]:
al

array([2, 4, 6, 8])

In [22]:
np.sum(al)                   #syntax: np.sum(array)

20

# Dot product  2*2

In [24]:
a1=np.array([[10,20],[30,40]])          # 2,2
a2=np.array([[1,2],[3,4]])              # 2,2

print("Array1\n",a1)
print("Array2\n",a2)

Array1
 [[10 20]
 [30 40]]
Array2
 [[1 2]
 [3 4]]


In [25]:
np.dot(a1,a2)

array([[ 70, 100],
       [150, 220]])

# Dot product 3*2

In [27]:
a1=np.array([[10,20],[30,40],[4,6]])          #  shape (3,2)
a2=np.array([[1,2],[3,4]])                    # shape(2,2)
a=np.dot(a1,a2)

In [28]:
print(a)
print(a1.shape)
print(a2.shape)
print(a1.ndim)
print(a2.ndim)

[[ 70 100]
 [150 220]
 [ 22  32]]
(3, 2)
(2, 2)
2
2


In [29]:
a1=np.array([[10,20],[30,40],[4,6]])               # shape 3*2
a2=np.array([[1,2],[3,7],[3,5]])                   # shape 3*2
a3=np.array([[1,2,3],[3,4,6]])                     # shape 2*3


In [30]:
a12=np.dot(a1,a3)
a12

array([[ 70, 100, 150],
       [150, 220, 330],
       [ 22,  32,  48]])

In [31]:
a12.shape

(3, 3)

In [32]:
z=np.dot(a12,a2)
z

array([[ 820, 1590],
       [1800, 3490],
       [ 262,  508]])

In [33]:
z.shape

(3, 2)

# Zeros

In [35]:
a=np.zeros((4,3),dtype="int")
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [36]:
a=np.zeros((4),dtype="int")
a

array([0, 0, 0, 0])

In [37]:
a=np.zeros((4,3,2),dtype="int")
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [38]:
a=np.zeros((4,3,3),dtype="int")
a

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [39]:
a=np.zeros((4,3),dtype="int")
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Ones

In [41]:
np.ones(5,dtype="int")

array([1, 1, 1, 1, 1])

In [42]:
np.ones([2,3],dtype="int")

array([[1, 1, 1],
       [1, 1, 1]])

In [43]:
np.ones([2,3,3],dtype="int")

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

# Identity

In [45]:
np.eye(5,dtype="int")                 # difference between identity and  eye difference

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [46]:
np.identity(5,dtype="int")      # but in indeb=ntity matrix does not followed by eye matrix .this is means main difference

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [47]:
np.eye(5,k=3,dtype="int") #  k :- partmeter is hepls set diagonally values but does not support in indentity the values. 

array([[0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# 4. np.arange

In [49]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [50]:
2,3
3,2
3,3
2,2


(2, 2)

In [58]:
q=([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])
a=q.reshape(2,6)
a

AttributeError: 'list' object has no attribute 'reshape'

In [54]:
array1=np.linspace(1,50,num=25,retstep=True)
array1

(array([ 1.        ,  3.04166667,  5.08333333,  7.125     ,  9.16666667,
        11.20833333, 13.25      , 15.29166667, 17.33333333, 19.375     ,
        21.41666667, 23.45833333, 25.5       , 27.54166667, 29.58333333,
        31.625     , 33.66666667, 35.70833333, 37.75      , 39.79166667,
        41.83333333, 43.875     , 45.91666667, 47.95833333, 50.        ]),
 2.0416666666666665)

In [60]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [62]:
a=np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [64]:
np.arange(10,20)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [88]:
array1=np.linspace(100,200,num=10)
array1

array([100.        , 111.11111111, 122.22222222, 133.33333333,
       144.44444444, 155.55555556, 166.66666667, 177.77777778,
       188.88888889, 200.        ])

In [115]:
import math
linspace
dict={"zeros": np.zeros(10),
      "Ones": np.ones(10),
      "Arange": np.arange(10,20),
      "Linspace":np.linspace(100,200,num=10,)}
dict

NameError: name 'linspace' is not defined

# 8.1 random

In [101]:
np.random.rand(1,3,2)

array([[[0.37421915, 0.31529922],
        [0.36224214, 0.57515844],
        [0.41191508, 0.25316053]]])

In [103]:
np.random.rand(1,3)

array([[0.14053772, 0.51454838, 0.32121492]])

In [105]:
np.random.rand(2,3,2)

array([[[0.74806557, 0.81226722],
        [0.0887798 , 0.33470264],
        [0.14895979, 0.35578771]],

       [[0.32611819, 0.90318682],
        [0.11943313, 0.6604865 ],
        [0.20226453, 0.39915008]]])

In [107]:
np.random.rand(2,3,2)

array([[[0.46102541, 0.52221956],
        [0.52986591, 0.08102358],
        [0.42716994, 0.37228861]],

       [[0.64585834, 0.83276018],
        [0.531159  , 0.72250207],
        [0.22016537, 0.81889255]]])

In [109]:
np.random.rand(2,3,3)

array([[[0.09771251, 0.1000898 , 0.75572636],
        [0.24204821, 0.64580489, 0.31682331],
        [0.99954799, 0.87701735, 0.32848717]],

       [[0.68208222, 0.88995663, 0.57490493],
        [0.3149186 , 0.57617673, 0.36442289],
        [0.12963274, 0.7081824 , 0.07695269]]])

In [119]:
q=np.round (np.random.rand(1,3,2),2)
q

array([[[0.65, 0.32],
        [0.22, 0.48],
        [0.17, 0.49]]])

In [123]:
q[0][0]

array([0.65, 0.32])

In [137]:
q[0][2]

array([0.17, 0.49])

In [157]:
q[0][1]

array([0.22, 0.48])

In [143]:
np.round(22321.325667,3)

22321.326

In [145]:
np.sqrt(225)

15.0

In [147]:
np.cbrt(225)

6.082201995573399

In [149]:
np.power(2,3)

8

In [151]:
np.median(a1)

15.0

In [159]:
np.mean(a1)

18.333333333333332

# 8.2 Random int

In [167]:
np.random.randint(1,25)

9

In [171]:
np.random.randint(1,25,size=(2,3))

array([[ 3, 17, 22],
       [ 7, 18, 13]])

In [173]:
np.random.randint(1,25,size=(2,))

array([16, 22])

In [175]:
np.random.randint(1,25,size=(2,))

array([15, 24])

In [ ]:
random.rand()                      #  difference between rand() , randint()
random.randint() 

In [178]:
arr1=np.random.randint(10,50,size=3)
arr1

array([26, 29, 43])

In [186]:
l1=arr1.tolist()
l1

[26, 29, 43]

In [190]:
" ".join([str(i) for i in l1])

'26 29 43'